language: java
jdk:
  - openjdk17
script:
  - sudo ./mvnw clean install
  - sudo ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker
  - sudo ./java -Dserver.port=8080 -jar target/movie-0.0.1-SNAPSHOT.jar

before_script: sudo chmod +x mvnw

#script:
#  - sudo ./mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#  - sudo ./mvn -Dflyway.configFiles=flyway.properties
#  - sudo ./mvn -Dflyway.user=user -Dflyway.password=password
#  - sudo ./mvn -Dflyway.schemas=schema
#  - sudo ./mvn test
#  - sudo ./mvn run -8080:8080 java-docker
#  - sudo docker build --tag java-docker .
#  - sudo docker images
#  - sudo docker run -8080:8080 java-docker
#  - sudo docker-machine ls
#  - curl --request GET --url https://murmuring-wave-33617.herokuapp.com/ --header 'content-type: application/json'
#

after_success: bash <(curl -s https:/spring-movielang.herokuapp.com/)
