language: java

matrix:
  include:
    - jdk: openjdk11
      os: linux
    - jdk: openjdk11
      os: osx
    - jdk: oraclejdk11

before_script: sudo chmod +x mvn

script:
  - sudo ./mvnw clean install -B
  - sudo ./mvn clean package -X
  - sudo ./mvn test
  - sudo docker build --tag java-docker .
  - sudo docker run -8080:8080 java-docker