spring:
  main:
    banner_mode: off

  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    url: jdbc:postgresql://ec2-18-235-114-62.compute-1.amazonaws.com:5432/dbgo3fr277jh86
    username: xhhiprtyikbzhv
    saltedPassword: N2U4MGNmYWVjYjA1YTNhMmVkMDgyYzkxNGQwN2Q1MjQ1ZjEyZmI3YzQxZjA3MTQwNDdhMzgwOTY0ODFhZTdmOA=
    ddl-auto: none
    show-sql: true
    format-sql: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true

logging:
  level:
    org:
      hibernate:
       SQL: debug
#       type: trace
      springframework: INFO

jwt:
  secret: 42