spring:
  main:
    banner_mode: off
  datasource:
    url: jdbc:postgresql://ec2-18-235-114-62.compute-1.amazonaws.com:5432/dbgo3fr277jh86
    username: xhhiprtyikbzhv
    password: 7e80cfaecb05a3a2ed082c914d07d5245f12fb7c41f0714047a38096481ae7f8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftlh

logging:
  level:
    org:
      hibernate:
       SQL: debug
#       type: trace